# -*- coding: utf-8 -*-
"""
Created on Sat Mar 05 20:16:28 2016

@author: Don Waldron
"""

# Here we provide the necessary imports.
import sys
from PyQt4      import QtGui

import BmiUiCallbacks as cb

# Class Ui_MainWindow is autogenerated from QT Designer 4.8.7
from ui.Ui_MainWin import Ui_MainWindow 

# instantiate GUI Object
BmiGui = Ui_MainWindow()


def run(argv): 

   app        = QtGui.QApplication(sys.argv)
   MainWindow = QtGui.QMainWindow()
   
   BmiGui.setupUi(MainWindow)
   
   # Bind events to call-backs
   BmiGui.pushButton_CalculateBmi.clicked.\
                     connect(cb.pushbutton_calc_bmi_clicked_callback)

   # Display the GUI
   MainWindow.show()
   
   app.exec_()

    

