# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MainWin.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(383, 289)
        MainWindow.setMouseTracking(False)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setProperty("toolTipDuration", 5)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.pushButton_CalculateBmi = QtGui.QPushButton(self.centralwidget)
        self.pushButton_CalculateBmi.setGeometry(QtCore.QRect(10, 110, 75, 23))
        self.pushButton_CalculateBmi.setObjectName(_fromUtf8("pushButton_CalculateBmi"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 50, 71, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 151, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.doubleSpinBox_Height_Inches = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_Height_Inches.setGeometry(QtCore.QRect(160, 10, 41, 22))
        self.doubleSpinBox_Height_Inches.setDecimals(0)
        self.doubleSpinBox_Height_Inches.setMaximum(11.0)
        self.doubleSpinBox_Height_Inches.setObjectName(_fromUtf8("doubleSpinBox_Height_Inches"))
        self.spinBox_Height_Feet = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_Height_Feet.setGeometry(QtCore.QRect(80, 10, 42, 22))
        self.spinBox_Height_Feet.setToolTip(_fromUtf8(""))
        self.spinBox_Height_Feet.setMinimum(3)
        self.spinBox_Height_Feet.setMaximum(7)
        self.spinBox_Height_Feet.setSingleStep(1)
        self.spinBox_Height_Feet.setProperty("value", 5)
        self.spinBox_Height_Feet.setObjectName(_fromUtf8("spinBox_Height_Feet"))
        self.doubleSpinBox_Weight = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_Weight.setGeometry(QtCore.QRect(80, 50, 62, 22))
        self.doubleSpinBox_Weight.setDecimals(0)
        self.doubleSpinBox_Weight.setMaximum(900.0)
        self.doubleSpinBox_Weight.setProperty("value", 100.0)
        self.doubleSpinBox_Weight.setObjectName(_fromUtf8("doubleSpinBox_Weight"))
        self.textBrowser_BmiResults = QtGui.QTextBrowser(self.centralwidget)
        self.textBrowser_BmiResults.setGeometry(QtCore.QRect(90, 110, 61, 31))
        self.textBrowser_BmiResults.setObjectName(_fromUtf8("textBrowser_BmiResults"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(210, 20, 47, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(160, 110, 221, 129))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_bmi_1 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_bmi_1.setObjectName(_fromUtf8("label_bmi_1"))
        self.verticalLayout.addWidget(self.label_bmi_1)
        self.label_bmi_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_bmi_2.setObjectName(_fromUtf8("label_bmi_2"))
        self.verticalLayout.addWidget(self.label_bmi_2)
        self.label_bmi_3 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_bmi_3.setObjectName(_fromUtf8("label_bmi_3"))
        self.verticalLayout.addWidget(self.label_bmi_3)
        self.label_bmi_4 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_bmi_4.setObjectName(_fromUtf8("label_bmi_4"))
        self.verticalLayout.addWidget(self.label_bmi_4)
        self.label_bmi_5 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_bmi_5.setObjectName(_fromUtf8("label_bmi_5"))
        self.verticalLayout.addWidget(self.label_bmi_5)
        self.label_bmi_6 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_bmi_6.setObjectName(_fromUtf8("label_bmi_6"))
        self.verticalLayout.addWidget(self.label_bmi_6)
        self.label_bmi_7 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_bmi_7.setObjectName(_fromUtf8("label_bmi_7"))
        self.verticalLayout.addWidget(self.label_bmi_7)
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(130, 20, 41, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 80, 451, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(150, 60, 47, 13))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionMenuHelpAbout = QtGui.QAction(MainWindow)
        self.actionMenuHelpAbout.setObjectName(_fromUtf8("actionMenuHelpAbout"))
        self.actionMenuFileExit = QtGui.QAction(MainWindow)
        self.actionMenuFileExit.setObjectName(_fromUtf8("actionMenuFileExit"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.spinBox_Height_Feet, self.doubleSpinBox_Height_Inches)
        MainWindow.setTabOrder(self.doubleSpinBox_Height_Inches, self.doubleSpinBox_Weight)
        MainWindow.setTabOrder(self.doubleSpinBox_Weight, self.textBrowser_BmiResults)
        MainWindow.setTabOrder(self.textBrowser_BmiResults, self.pushButton_CalculateBmi)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "BMI Calculator", None))
        MainWindow.setToolTip(_translate("MainWindow", "<html><head/><body><p>How is your health?</p></body></html>", None))
        self.pushButton_CalculateBmi.setText(_translate("MainWindow", "Calc BMI", None))
        self.label.setText(_translate("MainWindow", "Your Weight", None))
        self.label_2.setText(_translate("MainWindow", "Your Height", None))
        self.label_4.setText(_translate("MainWindow", "Inches", None))
        self.label_bmi_1.setText(_translate("MainWindow", "15 - 16    Severly Underweight", None))
        self.label_bmi_2.setText(_translate("MainWindow", "16 - 18.5  Underweight", None))
        self.label_bmi_3.setText(_translate("MainWindow", "18.5 - 25  Normal (Healthy Weight)", None))
        self.label_bmi_4.setText(_translate("MainWindow", "25 - 30     Overweight", None))
        self.label_bmi_5.setText(_translate("MainWindow", "30 - 35     Obese Class I", None))
        self.label_bmi_6.setText(_translate("MainWindow", "35 - 40     Obese Class II (severe)", None))
        self.label_bmi_7.setText(_translate("MainWindow", "over 40    Obese Class III (very severe)", None))
        self.label_11.setText(_translate("MainWindow", "Ft", None))
        self.label_5.setText(_translate("MainWindow", "Pounds", None))
        self.actionMenuHelpAbout.setText(_translate("MainWindow", "About", None))
        self.actionMenuFileExit.setText(_translate("MainWindow", "New...", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionSave.setText(_translate("MainWindow", "Save...", None))

